name: all_health_flutter
description: "An all-in-one health app for tracking and managing health data."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^6.0.0
  injectable: ^1.2.2
  flutter_dotenv: ^5.1.0
  go_router: ^13.2.1
  shared_preferences: ^2.2.0
  logging: ^1.2.0
  package_info_plus: ^6.0.0
  sqflite:

  cupertino_icons: ^1.0.6
  celest: ^0.4.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - shorebird.yaml