import 'package:flutter/material.dart';

class DnaList extends StatefulWidget {
  const DnaList({
    super.key,
  });

  @override
  State<DnaList> createState() => _DnaListState();
}

class _DnaListState extends State<DnaList> {
  @override
  Widget build(BuildContext context) {
    return Container(
        height: MediaQuery.of(context).size.height,
        width: MediaQuery.of(context).size.width,
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.only(left: 8.0, right: 8.0),
              child: SearchBar(),
            ),
            Expanded(
              child: ListView.builder(
                  itemCount: 10,
                  itemBuilder: (context, index) {
                    return SnpContainer();
                  }),
            ),
          ],
        ));
  }
}

class SnpContainer extends StatelessWidget {
  const SnpContainer({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Container(
          width: MediaQuery.of(context).size.width,
          height: 160,
          decoration: BoxDecoration(
            color: Colors.black26,
            borderRadius: BorderRadius.circular(10),
          ),
          child: Padding(
            padding: const EdgeInsets.all(4.0),
            child: Table(
              columnWidths: const <int, TableColumnWidth>{
                0: FlexColumnWidth(1),
                1: FlexColumnWidth(2),
              },
              children: [
                TableRow(children: [
                  Text("GSTP1"),
                  Text("Supplemental Vitamin E May Be Harmful"),
                ]),
                TableRow(children: [
                  Column(
                    children: [
                      Text("SNPs Involved"),
                      Text("rs1695(A;G)"),
                    ],
                  ),
                  Column(
                    children: [
                      Text("Information"),
                      Container(
                        height: 50,
                        width: MediaQuery.of(context).size.width,
                        child: ListView(children: [
                          Text(
                              "The glutathione S-transferase enzyme plays a significant role in the detoxification of various harmful compounds (either from the environment or generated by normal metabolism and immune function). Glutathione is one of the most potent antioxidant systems that the body possesses and is orders of magnitude more powerful than supplemental vitamin E (alpha-tocopherol). This genotype, rs1695(A;G), has been associated with possible harmful effects of supplemental vitamin E. There are common polymorphisms in the GSTP1 gene, which codes for the glutathione S-transferase enzyme. The variant form (G) of the rs1695 polymorphism, located in the coding region of the gene is thought to alter the activity of the enzyme. Individuals with the (A;A) genotype (approximately half of the population), have a form of the glutathione S-transferase enzyme with normal activity. In a study of 160 middle-aged men, subjects with the A allele had elevated levels of pro-inflammatory cytokines such as interleukin-6 (IL-6) in the blood when supplementing with vitamin E. However, those with the less active form of the GSTP1 enzyme (G;G genotype) had decreased IL-6 levels and thus, may receive an anti-inflammatory benefit from a low dose (75 IU) of supplemental vitamin E."),
                        ]),
                      ),
                    ],
                  ),
                ]),
              ],
            ),
          )),
    );
  }
}
